default_context:
  project_name: 'Base Project'
  project_slug: 'base-project'
  domain_main: 'base-project.com'
  domain_staging: 'stag.base-project.com'
  docker_swarm_stack_name_main: 'base-project-com'
  docker_swarm_stack_name_staging: 'stag-base-project-com'
  secret_key: 'b22d5599f6a235a4cd324f664dedbb5fec0f22b0434923021683ea64071952fb'
  first_superuser: 'admin@base-project.com'
  first_superuser_password: 'f7f8d03a254fc782d86b23f0ddb7d28ae1b9f23d9258aaa66640c5b1691f208a'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.base-project.com", "https://stag.base-project.com", "https://base-project.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@base-project.com'
  postgres_password: '5ae4a8fe7e234cb0b3aff098b1037294ef002be3e178cc2a7c3881d6987b3e2a'
  pgadmin_default_user: 'admin@base-project.com'
  pgadmin_default_user_password: 'f7f8d03a254fc782d86b23f0ddb7d28ae1b9f23d9258aaa66640c5b1691f208a'
  traefik_constraint_tag: 'base-project.com'
  traefik_constraint_tag_staging: 'stag.base-project.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:f7f8d03a254fc782d86b23f0ddb7d28ae1b9f23d9258aaa66640c5b1691f208a'
  sentry_dsn: ''
  docker_image_prefix: '[A[B'
  docker_image_backend: '[A[Bbackend'
  docker_image_celeryworker: '[A[Bceleryworker'
  docker_image_frontend: '[A[Bfrontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
