version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@6.15.3
executors:
  default-executor:
    docker:
      - image: circleci/buildpack-deps:stretch
jobs: 
  build-and-push:
    executor: default-executor
    steps: 
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
          version: 19.03.14
      - run: cd ./base-project/frontend
      - aws-ecr/build-and-push-image:
          repo: "${AWS_RESOURCE_NAME_PREFIX}"
          account-url: AWS_ECR_ACCOUNT_URL_ENV_VAR_NAME
          aws-access-key-id: ACCESS_KEY_ID_ENV_VAR_NAME
          aws-secret-access-key: SECRET_ACCESS_KEY_ENV_VAR_NAME
          region: AWS_REGION_ENV_VAR_NAME
          tag: "${CIRCLE_SHA1}"
workflows:
  build-and-push: 
    jobs:
      - build-and-push