version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@6.15.3
executors:
  default-executor:
    docker:
      - image: circleci/buildpack-deps:stretch
jobs: 
  build-and-push:
    executor: default-executor
    steps: 
      - checkout
      - setup_remote_docker:
          version: 19.03.14
      - aws-ecr/ecr-login:
          account-url: AWS_ECR_ACCOUNT_URL_ENV_VAR_NAME
          aws-access-key-id: ACCESS_KEY_ID_ENV_VAR_NAME
          aws-secret-access-key: SECRET_ACCESS_KEY_ENV_VAR_NAME
          region: AWS_REGION_ENV_VAR_NAME
      - run: 
          name: build image
          command: | 
            cd ./base-project/frontend
            docker build -t ${AWS_ECR_ACCOUNT_URL_ENV_VAR_NAME}:${CIRCLE_SHA1} .
      - run: 
          name: build image
          command: | 
            cd ./base-project/backend
            docker build -f backend.dockerfile -t ${AWS_ECR_ACCOUNT_URL_ENV_VAR_NAME_BACKEND}:${CIRCLE_SHA1} .
      - run: 
          name: build image
          command: | 
            cd ./base-project/backend
            docker build -f celeryworker.dockerfile -t ${AWS_ECR_ACCOUNT_URL_ENV_VAR_NAME_CELERY}:${CIRCLE_SHA1} .
      - run: 
          name: push images
          command: | 
            docker push ${AWS_ECR_ACCOUNT_URL_ENV_VAR_NAME}:${CIRCLE_SHA1}
            docker tag ${AWS_ECR_ACCOUNT_URL_ENV_VAR_NAME}:${CIRCLE_SHA1} ${AWS_ECR_ACCOUNT_URL_ENV_VAR_NAME}:latest
            docker push ${AWS_ECR_ACCOUNT_URL_ENV_VAR_NAME}:latest
            docker push ${AWS_ECR_ACCOUNT_URL_ENV_VAR_NAME_BACKEND}:${CIRCLE_SHA1}
            docker tag ${AWS_ECR_ACCOUNT_URL_ENV_VAR_NAME_BACKEND}:${CIRCLE_SHA1} ${AWS_ECR_ACCOUNT_URL_ENV_VAR_NAME_BACKEND}:latest
            docker push ${AWS_ECR_ACCOUNT_URL_ENV_VAR_NAME_BACKEND}:latest
            docker push ${AWS_ECR_ACCOUNT_URL_ENV_VAR_NAME_CELERY}:${CIRCLE_SHA1}
            docker tag ${AWS_ECR_ACCOUNT_URL_ENV_VAR_NAME_CELERY}:${CIRCLE_SHA1} ${AWS_ECR_ACCOUNT_URL_ENV_VAR_NAME_CELERY}:latest
            docker push ${AWS_ECR_ACCOUNT_URL_ENV_VAR_NAME_CELERY}:latest
workflows:
  build-and-push: 
    jobs:
      - build-and-push
          
