version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@6.15.3
build:
  context: ./base-project/frontend
workflows:
  build-and-deploy:
    jobs:
      - aws-ecr/build-and-push-image:
          repo: "${AWS_RESOURCE_NAME_PREFIX}"
          account-url: AWS_ECR_ACCOUNT_URL_ENV_VAR_NAME
          aws-access-key-id: ACCESS_KEY_ID_ENV_VAR_NAME
          aws-secret-access-key: SECRET_ACCESS_KEY_ENV_VAR_NAME
          region: AWS_REGION_ENV_VAR_NAME
          dockerfile: "./frontend/Dockerfile"
          path: "./frontend"
          tag: "${CIRCLE_SHA1}"
          